language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - tree
    packages:
      - libgnome-keyring-dev
      - clang

addons:
  apt:
    packages:
    - tree

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build
  - ../run_tests.sh
