language: cpp

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-4.0
    packages:
      - libgnome-keyring-dev
      - clang-4.0
      - tree

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build
  - ../run_tests.sh
